### ISSUE TITLE
Statistics for Scripts Seem to Be Wrong

### ISSUE THREAD

**Issue by NickTheTurtle** [lindsaykwardell/clocktracker#341]
I might be missing something, but the statistics displayed on scripts seem to be wrong. For example, for S&V, the frequency for each role is about the same, which doesn't make sense since Townsfolk and Minions both should have a (much) higher frequency than the individual Demons. Furthermore, each win rate for each character is above 50%, which doesn't seem possible. When you click into each individual character, the rates of appearance does not match what's mentioned on the script.

**Comment by lindsaykwardell** [comment]
Thanks for raising this! I found the issue with how stats were being determined on the script page, and this should be resolved now. The fix is being deployed right now. Please let me know if things still look wrong to you!
