### ISSUE TITLE
HTTP Error 400 when trying to claim seat

### ISSUE THREAD

**Issue by Oldcustard** [lindsaykwardell/clocktracker#388]
I receive the following error when trying to claim a seat

> [PUT] "/api/games/97e07eec-c165-4d96-9489-5f3aa250d03a/claim_seat": 400

**Comment by lindsaykwardell** [comment]
I believe this is fixed in the next release, let me know if you have any further issues. Closing this for now. Thank you!

**Comment by Oldcustard** [comment]
Hi @lindsaykwardell, thanks for working on this. I don't think the claiming issue is totally I resolved. I seem to be only able to claim seats in games where the person who uploaded the game is not the storyteller. In one game where I could claim a seat, I received an error "There was a problem claiming this seat: " but then no error message. However, when I refreshed the page, it looked like I did end up claiming the seat, although the game does not show up on my profile.

Hope this information is helpful!

**Comment by Oldcustard** [comment]
Additional debugging! It's not the uploader being the storyteller preventing me from claiming, it's any game that I click on where the storyteller is the icon. So if I go to the profile of a player who was in that game, and select the game from there, I can then claim a seat in that game
